apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: art-run-worker
  name: art-run-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: art-run-worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: art-run-worker
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/REPOSITORY/IMAGE:TAG
          name: art-run-worker
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: art-run-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: art-run-encrypt-key # from secret
                  key: ENCRYPT_KEY
          ports:
            - containerPort: 8080