apiVersion: v1
kind: Service
metadata:
  name: art-run-worker-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: art-run-worker