spring:
  profiles:
    default: local
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: map-matching-group
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: 10.80.10.5:9092
    consumer:
      group-id: map-matching-group
